export const categoriesEn = ["All", "Love", "Personality", "Mind & Love", "Charm & Vibe", "Love Luck", "Social Media", "Dark Side", "Money", "Career", "Life & Fun", "Oshi & Fandom"]

export const scenesEn = [
  { id: "all", label: "All", emoji: "🌀", description: "See every quiz" },
  { id: "couple", label: "Couples", emoji: "💑", description: "Fun to enjoy together" },
  { id: "drinking", label: "Drinks with friends", emoji: "🍻", description: "Great icebreakers for a party" },
  { id: "friends", label: "Friends", emoji: "👥", description: "Easy to riff on with friends" },
  { id: "solo", label: "Solo", emoji: "🌙", description: "Dig a little deeper, just for you" },
  { id: "share", label: "Share it", emoji: "📣", description: "Results that are easy to post" },
]

export const sceneSetsEn = [
  { id: "couple", title: "Quizzes for couples", emoji: "💑", text: "A set about love style, jealousy, and distance that gets the conversation going." },
  { id: "drinking", title: "Quizzes for parties", emoji: "🍻", text: "A fun, easy set for drinks with friends." },
  { id: "solo", title: "Quizzes to take alone", emoji: "🌙", text: "A set for digging into feelings you don't usually show anyone." },
]

export const diagnosesEn = [
  {
    id: "hidden-personality",
    title: "Hidden Self Test",
    category: "Personality",
    emoji: "🌓",
    scenes: ["drinking", "friends", "solo", "share"],
    description: "Discover the other side of yourself that you usually keep hidden.",
    questions: [
      "I don't show my true feelings much when meeting someone for the first time",
      "I easily notice when people are lying or something feels off",
      "I get tired out if I don't have time alone",
      "When I'm angry, I go quiet and keep my distance",
      "I have a side of myself I show no one",
      "People say I seem kind, but inside I'm pretty calm and calculating",
      "I go along with others, but I'm always judging things in my head",
      "I know how to pick the moment to show what I'm really capable of",
    ],
    results: ["Honest Villager Type", "Quiet Observer Type", "Hidden Ruler Type", "I Answer to No One Type"],
  },
  {
    id: "love-complicated",
    title: "Complicated Love Test",
    category: "Love",
    emoji: "💘",
    scenes: ["couple", "friends", "solo", "share"],
    description: "You like them but can't be honest about it. Find out how complicated your love life really is.",
    questions: [
      "I overthink my replies to someone I like",
      "My mood goes up and down based on one word from them",
      "I want to be babied but I act tough instead",
      "I cool off when they chase me, but get anxious when they pull away",
      "I tend to check social media a lot while I'm dating someone",
      "If their reply is slow, I go back and reread old messages",
      "I say I'm fine, really when I'm actually lonely",
      "I overanalyze an offhand comment and hold a one-person post-mortem about it",
    ],
    results: ["Easygoing Villager Type", "Playing-It-Cool Type", "Swamp-Adjacent Type", "Swamp Dweller Type"],
  },
  {
    id: "menhera-level",
    title: "Clinginess Level Test",
    category: "Mind & Love",
    emoji: "🫧",
    scenes: ["couple", "friends", "solo"],
    description: "You want attention but can't say it. Find out how much reassurance you need.",
    questions: [
      "I get anxious if a message isn't marked as read",
      "I'm very sensitive to my crush's mood",
      "I say I'm fine when I'm really not",
      "I act tough when I'm actually feeling lonely",
      "I get anxious when there isn't much affection shown",
      "If their mood seems low, I assume it might be my fault",
      "There are moments I suddenly stop caring about everything",
      "I crave proof that I'm loved",
    ],
    results: ["Stable Mind Type", "Slightly Read-Receipt-Anxious Type", "Emotional Rollercoaster Type", "Reassurance-Addicted Type"],
  },
  {
    id: "dangerous-man",
    title: "Dangerous Charm Test",
    category: "Charm & Vibe",
    emoji: "🕶️",
    scenes: ["couple", "drinking", "friends", "share"],
    description: "You can't tell what they're thinking, but you're drawn in anyway. Find out how strong your pull toward dangerous charm is.",
    questions: [
      "People say they can't tell what I'm thinking",
      "I tend to give off a different vibe than everyone else",
      "There's a gap between how kind and how cold I can be",
      "I value having my own worldview",
      "I'm a little pleased when someone calls me dangerous",
      "I'm very selective about who I show my emotions to",
      "I'm bad at explaining everything about myself to people",
      "I've been told I'm hard to approach but hard to stop thinking about",
    ],
    results: ["Safe-Zone Observer Type", "Slightly Risky Type", "Swamp Warning Type", "Dangerous Swamp Dweller Type"],
  },
  {
    id: "popularity-season",
    title: "Popularity Season Test",
    category: "Love Luck",
    emoji: "🌹",
    scenes: ["couple", "friends", "share"],
    description: "Is your popular season now, or still to come? Find out when your charm is set to bloom.",
    questions: [
      "I've been getting more compliments lately",
      "I'm starting to understand what look suits me",
      "I want to work on improving myself",
      "I've had more plans to see people lately",
      "I feel like I could change right now",
      "I feel more confident about first impressions than I used to",
      "I've had the feeling lately that people are watching me",
      "I've become more positive about dating",
    ],
    results: ["Business as Usual Type", "Slight Popularity Signs Type", "Popularity Wave Incoming Type", "Peak Popularity Season Type"],
  },
  {
    id: "sns-approval",
    title: "Social Media Approval Test",
    category: "Social Media",
    emoji: "📱",
    scenes: ["drinking", "friends", "share"],
    description: "Likes, view counts, subtle hints. Find out how much you crave approval on social media.",
    questions: [
      "I check likes and comments repeatedly after posting",
      "I can't help checking who viewed my story",
      "I want to hint at things in posts that I can't say directly",
      "If a post doesn't get much reaction, I think I shouldn't have posted that",
      "Even a casual-looking post sometimes carries a hidden meaning",
      "I carefully adjust the photo, caption, and timing before posting",
      "I care whether the person I want to see it actually saw it",
      "I compare how my posts do against other people's",
    ],
    results: ["Social Media Easygoing Type", "Slightly Concerned Type", "Subtle Hinter Type", "Full Self-Display Type"],
  },
  {
    id: "dark-fall",
    title: "Falling to the Dark Side Test",
    category: "Dark Side",
    emoji: "🌑",
    scenes: ["drinking", "friends", "solo"],
    description: "Are you still on the light side, or about to awaken as the final boss?",
    questions: [
      "There are moments I want to throw everything away",
      "I try not to expect too much from people",
      "I've become more jaded than I used to be",
      "I feel exhausted inside even when I'm laughing",
      "I have some dark feelings inside me",
      "Sometimes I think kind people just end up losing out",
      "When I really get angry, I go very cold",
      "There's someone I've wanted to quietly distance myself from lately",
    ],
    results: ["Staying in the Light Type", "Edge of Darkness Type", "Deepening Loneliness Type", "Dark Awakening Type"],
  },
  {
    id: "money-luck",
    title: "Money Luck Type Test",
    category: "Money",
    emoji: "💰",
    scenes: ["friends", "solo"],
    description: "Earn it, save it, or spend it? Find out your relationship with money.",
    questions: [
      "I want to buy something as soon as I see it",
      "I get anxious about money in the future",
      "I don't dislike thinking about ways to earn money",
      "I'd rather spend on experiences than save",
      "I'm drawn to stories about making big money",
      "Having money gives me peace of mind",
      "I don't really keep track of my monthly finances",
      "I get a little excited by stories of hitting it big",
    ],
    results: ["Steady Saver Type", "Slight Spender Type", "Rising Fortune Type", "Awakened Fortune Type"],
  },
  {
    id: "work-style",
    title: "Ideal Work Style Test",
    category: "Career",
    emoji: "🧭",
    scenes: ["friends", "solo"],
    description: "Office worker? Salesperson? Creative? Find out the work style that suits you.",
    questions: [
      "I find it hard to keep doing the same task over and over",
      "I don't mind talking to people to get things moving",
      "Work where I think and act for myself suits me",
      "I like turning ideas into something real",
      "I perform better with more freedom",
      "An environment with too many detailed rules exhausts me",
      "I get fired up when I can see numbers and results",
      "People often come to me for advice",
    ],
    results: ["Steady Employee Type", "Idea Generator Type", "Creative Planner Type", "Entrepreneurial Type"],
  },
  {
    id: "life-bug",
    title: "Life Glitch Level Test",
    category: "Life & Fun",
    emoji: "🎮",
    scenes: ["drinking", "friends", "share"],
    description: "Wrong choices? Main character energy? Find out how glitchy your life really is.",
    questions: [
      "I tend to get caught up in unusual events",
      "I think I've made the wrong choice somewhere in life",
      "Things suddenly turn into a strange, confusing situation",
      "My failure stories tend to become good material",
      "I think I have some strange kind of luck",
      "People have told me my life is full of ups and downs",
      "I feel like my life won't end in an ordinary way",
      "Somehow, one way or another, I always come out okay",
    ],
    results: ["Normal Playthrough Type", "Frequent Wrong Choices Type", "Multiple Life Errors Type", "Full Glitch Awakening Type"],
  },
  {
    id: "oshikatsu-type",
    title: "Oshi Fan-Style Quiz",
    category: "Oshi & Fandom",
    emoji: "🌟",
    scenes: ["friends", "solo", "share"],
    description: "Event-goer? Collector? Theorist? Find out your fan style and how deep in the fandom you really are.",
    questions: ["I want to attend my oshi's events whenever possible", "I have bought multiple copies of merch: one to use, one to keep", "I think deeply about the meaning behind my oshi's words and actions", "Once I start talking about my oshi, I can't stop", "I want to celebrate my oshi's birthday and anniversaries properly", "I have run out of space to store my oshi's merch", "I feel the urge to express my love for my oshi in writing or art", "I have pulled (or almost pulled) a friend into my fandom"],
    results: ["Casual Watcher Type", "Event-Goer Type", "Full-Attendance Type", "Life-Devotion Type"],
  },
  {
    id: "reply-type",
    title: "Reply Style Quiz",
    category: "Social Media",
    emoji: "💬",
    scenes: ["friends", "drinking", "share"],
    description: "Instant replier? Lord of unread messages? Find out your texting style, expressed as a font.",
    questions: ["My replies tend to get long", "I often reply with short words like 'ok' or 'kk'", "I express feelings with stickers more than words", "Text feels lonely without emojis or kaomoji", "I want to respond to everything in their message", "Getting the point across is enough", "I collect favorite stickers", "The amount of emoji changes with my mood"],
    results: ["Ultra-Thin Mincho Type", "Round Gothic Type", "Pop Type", "Heavy Gothic Type"],
  },
  {
    id: "crush-misread",
    hidden: true,
    title: "Crush Signal Misread Quiz",
    category: "Love",
    emoji: "💌",
    scenes: ["friends", "drinking", "share"],
    description: "Was that kindness a sign, or just politeness? A free love quiz that measures how often you misread the signals.",
    questions: ["When someone is kind to me, I think 'wait, maybe...'", "A streak of likes feels like a sign of interest", "I take 'let's hang out sometime' as an actual plan", "Running into someone by chance feels like destiny", "Just sitting next to someone makes me a little conscious of them", "I measure affection by reply speed", "I take 'you can always talk to me' as special treatment", "I end up checking birthday or zodiac compatibility"],
    results: ["Cool Judge Type", "Like-Watcher Type", "Literal Translator Type", "Destiny Factory Type"],
  },
  {
    id: "dark-depth",
    hidden: true,
    title: "Darkness Depth Quiz",
    category: "Dark Side",
    emoji: "🌊",
    scenes: ["drinking", "friends", "solo", "share"],
    description: "How many meters deep is the darkness in your heart? A free personality test that measures your inner depths on a deep-sea scale.",
    questions: ["The commentary in my head never stops", "I remember old grudges vividly", "I doubt people's good intentions first", "I sometimes weigh gains and losses before acting", "I say my real thoughts disguised as jokes", "I said 'I forgive you' but I haven't forgotten", "I never show anyone my full true feelings", "I'm good at laying groundwork in advance"],
    results: ["Leaky Inner Voice Type", "Budding Grudge Type", "Iron Heart Type", "Trench Mastermind Type"],
  },
]

export const optionsEn = [
  { label: "Not at all", value: 0 },
  { label: "A little true", value: 1 },
  { label: "Pretty true", value: 2 },
  { label: "Totally me", value: 3 },
]
