export const randomCommentPoolsEn = {
  "love-complicated": [
    "While waiting for a reply, you've basically built a war room in your head.",
    "Your skill at pretending you're fine despite liking someone has grown weirdly strong.",
    "You turn one offhand comment into the material for a whole mental drama series.",
    "You say \"I don't really care\" while actually caring a lot.",
    "Only your crush's notifications seem to be wired straight to your heart rate.",
    "Cool when they chase, anxious when they pull away — your romantic brakes and gas pedal stay busy.",
    "Being honest would be faster, but somehow you take the complicated route every time.",
    "Your whole day can hinge on checking your crush's mood.",
    "You have a real talent for reading way too much into your crush's words.",
    "Only during romance do your inner detective and screenwriter switch on at the same time.",
    "You type a reply, delete it, type it again, delete it, and end up with something totally plain.",
    "You actually want to see them, but you play it cool instead.",
    "You try to analyze the exact warmth behind their \"lol.\"",
    "Only around your crush do your messages suddenly get overly careful.",
    "Part of you doesn't want to double-text, and part of you wants to send it right now.",
    "You make your own personal romance weather forecast based on their reply speed.",
    "Around your crush, you become a little more high-maintenance than usual.",
    "You want to be honest, but you stop yourself after imagining the mood afterward.",
    "\"I don't want to seem clingy\" is exactly what makes you harder to read.",
    "You're strangely quick to notice your crush's social media updates.",
    "You watch their actions more than their words and start drawing your own conclusions.",
    "You try to read whether there's a chance from their punctuation alone.",
    "Kindness makes you happy, but anxiety tends to come along with it.",
    "Your usual calm glitches out a little the moment romance is involved.",
    "You think you're playing it cool, but really you're the one who's shaken.",
    "You overthink how you'll be perceived, so your honest words come out late.",
    "Around your crush, the more you try to hide your feelings, the more they show.",
    "You start predicting their reply before the message is even marked read.",
    "You notice their smallest changes so much that it wears you out.",
    "You act like you don't care, but inside you're keeping a detailed log.",
    "In romance, your brain runs in constant emergency-meeting mode.",
    "The moment you say \"I'm fine\" is often exactly when you're not.",
    "One word from them can make you happy, and that same word can make you anxious.",
    "Around your crush, you get a stubborn urge not to lose at some invisible game.",
    "You forget how to ask for affection honestly and send roundabout signals instead.",
    "You're so sensitive to shifts in romantic temperature that your own seasons keep changing.",
    "You actually like them in an obvious way, but you try to make it look unclear.",
    "In romance, the analysis committee in your head works overtime.",
    "You replay one line from your crush over and over, adding new meanings each time.",
    "The moment you realize you're overcomplicating things, that's already a sign of talent.",
  ],
  "hidden-personality": [
    "You look calm on the outside, but inside you're watching everyone quite coolly.",
    "The more you're smiling, the more you're actually observing people's true feelings.",
    "You look kind, but there's a proper judge sitting in your heart.",
    "You stay quiet until you go all in, and the mood shifts completely once you do.",
    "You seem to go along with others, but you actually have quite firm standards of your own.",
    "It's less a hidden face and more a set of hidden stats running high.",
    "When angry, you're more likely to quietly distance yourself than make a scene.",
    "Your expression stays calm, but your mental notebook keeps a thorough record.",
    "The face you show everyone and the face you show a chosen few are different.",
    "You look like an ordinary villager, but you actually grasp what's happening behind the scenes.",
    "The quieter you are, the more your mind is actually sorting things out.",
    "You're good at going along with the room, but that doesn't mean your heart fully agrees.",
    "You seem kind, but your boundaries are actually quite clear.",
    "You watch people closely, so you notice something off about them early.",
    "You're quite selective about who gets to see your true feelings.",
    "The quieter you are, the more you're actually in information-gathering mode.",
    "Instead of showing anger outwardly, you take a big step back emotionally.",
    "You go along with someone while quietly holding a different answer inside.",
    "Smiling doesn't necessarily mean you've forgiven everything.",
    "It takes quite a while for you to show your true self.",
    "The habits hidden beneath your first impression run fairly strong.",
    "Because you can read the room, you're also quick to judge people who can't.",
    "Your outer face is calm; your inner face is quite strategic.",
    "Once someone earns your trust, the amount you share with them suddenly increases.",
    "Even if you say \"it's fine,\" it hasn't necessarily left your internal record.",
    "When you stay silent, it's not that you're losing — you're observing.",
    "You separate the places where you show your true feelings from the places you don't.",
    "Behind your kindness lies a fairly cool sense of judgment.",
    "Before emotion, situational analysis kicks in first.",
    "You naturally switch the self you show people depending on the scene.",
    "When you flip the switch to go all in, the gap from your usual self is huge.",
    "You watch the gap in someone's attitude more than their words.",
    "The moment you stop liking someone, you tend to get quietly, extra polite.",
    "You're skilled at managing your expression, so your true feelings are hard to catch.",
    "You don't hide your true feelings out of weakness — you're choosing where they're worth showing.",
    "You have your own private screening process before you trust someone.",
    "Inside, you're a lot more severe in your judgments than people assume.",
    "You're a bit like a hidden overseer wearing a villager's clothes.",
    "You look soft, but your core doesn't budge easily.",
    "Kindness and wariness coexist in you, making you a hard type to read.",
  ],
  "menhera-level": [
    "The more you act fine, the more your heart is actually waiting for a notification sound.",
    "Your mental weather for the day changes based on your crush's reply speed.",
    "After saying \"I'm fine,\" you're the type to realize on your own that you're not.",
    "You want reassurance, but you take the roundabout route so you won't seem clingy.",
    "You have a habit of acting a little tough to hide your loneliness.",
    "When your crush seems down, a meeting starts in your head about whether it's your fault.",
    "You just want to feel at ease, but your way of checking can come out a bit awkward.",
    "The world gets a little kinder the instant a notification arrives.",
    "When anxious, you sometimes dig all the way back through old conversations.",
    "Your true feeling is \"pay attention to me,\" but it comes out looking like something else.",
    "There's a tiny detective in your heart, always collecting evidence that you're loved.",
    "The messages you send the instant your emotions spike tend to read a bit strong later.",
    "You're remarkably quick at assuming you've been disliked.",
    "You tend to seek an emotional charger only from the person you like.",
    "The lonelier you are, the harder it can be to just say you're lonely.",
    "Some days you wish you could see the exact battery level of your affection meter.",
    "When anxious, imagination tends to outgrow the actual facts.",
    "Your strong desire to be cherished makes you sensitive to every reaction.",
    "You don't want to break the relationship — you just want reassurance.",
    "In romance, your notifications seem permanently set to maximum volume.",
    "You have a delicate antenna that picks up both reassurance and anxiety from a single word.",
    "The more you try not to seem heavy, the heavier your heart tends to feel.",
    "In the time before a reply comes, unnecessary stories start playing in your head.",
    "You really just want one word, but you end up trying to confirm it through their attitude.",
    "Your heart reacts instantly to your crush's smallest changes.",
    "The more anxious you are, the more often you check your phone.",
    "A lot of true feeling hides inside a casual \"it's fine.\"",
    "You're good at expressing your need for attention in a joking way.",
    "Your emotional battery drains fastest on days affection is scarce.",
    "Calm when reassured, and suddenly your inner committee convenes when anxious.",
    "Even without meaning to test someone, you end up watching their reaction closely.",
    "One read receipt from your crush can drag out a long meeting in your head.",
    "Part of you wants to vent your anxiety, part of you doesn't want to be disliked — they fight it out.",
    "Because your devotion runs deep, you're quite sensitive to shifts in their warmth.",
    "You keep past kind words tucked away in your heart's save folder.",
    "If you can let out your loneliness in small doses before it peaks, things get much easier.",
    "You can't help wondering where you rank among the people your crush cares about.",
    "A lukewarm reaction from them can make you doubt your own worth.",
    "You really just want reassurance, but the way you ask can come out a little strong.",
    "The stronger your wish to be loved, the harder it becomes to say it plainly.",
  ],
  "sns-approval": [
    "Checking reactions after posting has basically become a routine patrol.",
    "You tend to adjust the angle of a post so it reaches the one person you want to see it.",
    "Some days who saw it matters more than how many likes it got.",
    "You go looking for today's answer in your story's viewer list.",
    "Even when you don't mean to hint at anything, the people who notice, notice.",
    "The moment you think \"how will this look\" before posting, you're already a social-media villager.",
    "When reactions are thin, you start doubting yourself more than the post.",
    "You've posted things meant to land with exactly one person.",
    "You look calm on social media, but inside you're carefully tracking numbers and viewers.",
    "Whether that one person saw it changes your mood more than the like count does.",
    "For a few minutes after posting, part of your heart lives in the notification tab.",
    "The moment the person you wanted to see it does, that post has basically done its job.",
    "The posts you hesitate over deleting are often the ones with a bit more truth mixed in.",
    "What looks like a casual post might actually be a carefully calculated move.",
    "You save posts that get a good reaction as success stories in your head.",
    "You look at the order of story viewers and try to read meaning into it.",
    "Before you even post, you've already started imagining who will see it and how.",
    "You act natural on social media while quietly adjusting how you're presented.",
    "On days with few likes, the world looks a little colder.",
    "Your mood for the day can shift depending on whether that one person saw it.",
    "Sometimes the hidden theme of a post is really aimed at just one person.",
    "It's less a need for approval and more a ritual of confirming you exist.",
    "You act casual about social media, but inside you're fairly serious about it.",
    "Opening a post again and again after posting has stopped being a check and become a pilgrimage.",
    "You act like you're not watching, but you're actually watching the viewer list closely.",
    "Even without meaning to hint at anything, a little of your inner perfume leaks out.",
    "The value of a like changes depending on who it came from, more than the count.",
    "The posts you want to delete are often closer to your true feelings.",
    "Your social-media self and your real self have slightly different levels of polish.",
    "A good reaction can suddenly make the whole world look kinder.",
    "Posting is, in part, a way of confirming your own existence.",
    "You say \"I don't need people to see it,\" but you're genuinely happy when they do.",
    "Your focus while checking the viewer list might beat your focus at work.",
    "The shorter you make a caption, the more meaningful it ends up looking.",
    "A casual-looking photo can hide the feeling you actually want to show.",
    "It's a little unsatisfying when the one person you really want to see it doesn't.",
    "You act tough about social media, but you're fairly honest about how reactions affect you.",
    "There's an unconscious strategy behind the timing of your posts.",
    "Seeing someone else's post sometimes makes you rethink how you present yourself.",
    "Every time a like comes in, your self-esteem gets a small recharge.",
    "Your pretense of not caring about reactions gets a little sloppy sometimes.",
    "Because stories disappear, you find it easier to mix in your true feelings.",
    "Sometimes a post hides a \"only the right people will get this\" message.",
    "Checking the viewer list quickly is the one thing you're truly a pro at.",
    "The silence after posting quietly wears on your mental state.",
    "You look relaxed on social media, but inside you're on standby for a reaction.",
    "You're more sensitive to how you're seen than to other people's reactions.",
    "A little \"notice me\" is mixed into your posts sometimes.",
    "While making a post, you're already imagining its future viewers.",
    "Even after closing the app, part of your mind is still waiting for a notification.",
    "When likes don't come, you'd rather blame the timing than the post itself.",
    "Rather than say your true feelings directly, you leave a little of them in a post.",
    "You want to be seen, but being seen too much is embarrassing — a complicated social-media heart.",
    "The fact that a reaction reassures you is proof you hold citizenship in social-media village.",
    "Sometimes even you lose track of the line between hinting and an ordinary post.",
    "Part of a post might be an indirect message to someone specific.",
    "You look like you're playing around lightly on social media, but your emotional warmth shows through.",
    "The instant you spot a certain name among your viewers, you feel a small win.",
    "Hiding the part of you that cares about reactions is itself part of the need for approval.",
    "On the other side of every post, you genuinely hope someone will find you.",
  ],
  "dangerous-man": [
    "You know it's dangerous, yet there's a pull that keeps you a little interested.",
    "Before you even get close, a small alarm bell is already ringing somewhere in your heart.",
    "You can't look away from the gap between kindness and danger.",
    "When plain reassurance isn't enough, a dangerous vibe strangely hits the spot.",
    "You sometimes take someone's unreadable mood as a form of charm.",
    "You think you're watching from a step back, but you notice you've gotten a little closer.",
    "You sometimes lose track of the line between pushiness and reliability.",
    "The more unstable someone is, the harder it becomes to just leave them be.",
    "A little kindness after coldness tends to overwrite your judgment.",
    "You notice the warning signs, yet part of your heart is still on the scene.",
    "The more secrets someone has, the stronger your urge to chase after them.",
    "You find a kind of drama even in a mood most people would avoid.",
    "Your attention tends to drift toward someone a bit unreadable rather than someone reassuring.",
    "One word from them can trigger your caution and your anticipation at the same time.",
    "You're pulled more by a glimpse of weakness than by obvious kindness.",
    "The moment you think \"this might be dangerous\" is often exactly when you start thinking about them more.",
    "You try to keep your distance, but one notification can pull your heart right back.",
    "You don't mean to match their pace, but you notice you have anyway.",
    "You know you're standing at the edge of the swamp, yet you pretend not to look down.",
    "You sometimes mistake stimulation and anxiety for the excitement of being in love.",
    "You actually want stability, yet you react to a risky shift in temperature.",
    "Even seeing their careless side, you sometimes go looking for the kind part anyway.",
    "Thinking \"I want to be the one who understands them\" tends to pull you in deeper.",
    "The more wary you are, the bigger their small kindness starts to look.",
    "You don't want to chase them, yet their unreadable attitude keeps catching your attention.",
    "The more dangerous the romance, the better you get at making excuses to yourself.",
    "You tend to take their clumsiness as a kind of special vulnerability.",
    "Strong words or attitude can feel like a dominating kind of charm to you.",
    "You know you should walk away, yet you wait for one last word.",
    "Their fickle kindness can feel like a rare, special performance to you.",
    "You're more drawn by an unreadable reaction than by steady affection.",
    "You can sense a dangerous mood, yet your escape button always seems to lag a little.",
    "Seeing someone's darkness, you tend to think maybe you could be the one to hold it.",
    "Your calm self and the part of you that wants to sink into the swamp are in a tug of war.",
    "A dangerous person can sometimes look like the main character of a story to you.",
    "You can see every reason to say no, yet you go looking for a reason to see them anyway.",
    "The more chaotic their pace gets, the more your own feelings get pulled along.",
    "At the entrance to a dangerous romance, you're still able to turn back, yet you pause a little.",
    "Finding a safe love boring is a sign you've gotten too used to the stimulation.",
    "You have the ability to notice before you sink into the swamp. All that's left is trusting that instinct.",
  ],
  "popularity-season": [
    "You're still a small bud right now. Even unnoticed, the seed of your charm is growing properly.",
    "It's the eve of your popularity season. No flashy change yet, but your vibe is quietly coming together.",
    "Not in full bloom yet, but up close your charm is quietly showing through.",
    "You think it's business as usual, but from the outside your mood has softened a little.",
    "You don't need to force yourself to bloom right now. Charm that grows naturally pays off later.",
    "A modest kind of cuteness is showing. Not flashy, but there's a reassuring air people can approach.",
    "Like baby's breath, you don't need to be the star to soften the mood around you.",
    "Rather than eye-catching popularity, the kind of charm that only close people notice is showing.",
    "Your approachability is rising. The door to romance often opens first through a sense of ease.",
    "A pure, gentle air is showing. Even without pushing hard, you're steadily making a good impression.",
    "You have a vibe that doesn't make people tense around you. That's a quietly strong charm.",
    "You're leaving a good impression while staying yourself. An unforced charm is coming through.",
    "You have a lavender-like soothing quality. This is a period where being with you feels calming to others.",
    "The petals of your heart are opening little by little. Give yourself credit for how you've been changing lately.",
    "There are slight signs of popularity. A small reaction or conversation could spark something.",
    "A tulip-like freshness is showing. You don't need to force yourself to seem more mature than you are.",
    "Your compliment luck is rising. Instead of brushing it off, saying thank you honestly helps you bloom further.",
    "A marguerite-like honesty is your charm. Words without unnecessary decoration are making a good impression.",
    "Your likability is climbing steadily. You're the type who wins through everyday impressions rather than one big moment.",
    "You have a cosmos-like natural charm. Right now, easing off a little actually brings out more of your appeal.",
    "Signs of romance are appearing. Don't let a chance conversation or small connection pass by.",
    "Like cherry blossoms, this is a period where you can leave an impression in an unguarded moment. A casual remark can go a long way.",
    "A wave of popularity is approaching. If reactions around you start to shift, it's fine to ride that flow.",
    "A gerbera-like brightness is showing. Your smile and positivity are becoming your charm as they are.",
    "This is a period when you easily draw the eye. Simply carrying yourself with confidence makes your presence stand out more.",
    "You have a sunflower-like brightness. People near you naturally tend to pick up some of your energy.",
    "You're becoming easier to invite along. Casual plans or conversations could turn into a chance at romance.",
    "A white-lily-like elegance is showing. There's a special air about you that keeps people from approaching carelessly.",
    "Your chances at romance are increasing. Right now, moving a little rather than only waiting helps the flower bloom.",
    "Like a peony, your presence is softly expanding. Your gorgeousness is coming through naturally.",
    "You're entering the heart of your popularity season. Rather than holding back too much, it's fine to properly show your charm.",
    "A dahlia-like individuality is shining. This is a period when being yourself lands better than trying to fit in with everyone.",
    "Your romantic luck is quite strong. Don't fear their reaction — stepping forward a little can change how things unfold.",
    "A rose-like classic charm is showing. It might help to prepare yourself to receive some affection.",
    "Your power to draw people in through atmosphere is growing. Even without words, your charm comes across through the air around you.",
    "You have a lotus-like mystery. The part that's hard to read easily becomes the part people find intriguing.",
    "A beloved aura is really showing. Don't make yourself small — stay gentle and confident.",
    "You're approaching princess-flower mode. Not in an exaggerated way, but naturally being treasured by those around you.",
    "Your charm right now is closer to full bloom. When encounters, invitations, or compliments come, accept them honestly.",
    "The flower of your popularity season is really blooming. Without rushing, you can bloom most beautifully at your own pace.",
  ],
  "money-luck": [
    "This is a period when stacking up small amounts pays off. Organizing your daily spending connects to fortune more than one big win.",
    "Rather than growing money flashily, it helps to first grasp the flow of it. Try visualizing this month's spending.",
    "Waiting just a little before buying something you want can prevent wasteful purchases. Watch out for impulse buys.",
    "Your fortune leans toward protection right now. Reviewing your budget or fixed costs could free up more room than you'd expect.",
    "Spending money isn't inherently bad. Narrowing it down to things with high satisfaction leads to fewer regrets.",
    "This is a period when small gains are easy to pick up. Checking points, coupons, and campaigns could pay off.",
    "Sorting out the money you're spending without really noticing can clean up your financial flow quite a bit.",
    "Before increasing income, plugging the leaks in spending tends to show results faster. Start by reviewing your monthly fixed costs.",
    "You have shopping luck, but choosing based on real need rather than just cheapness stabilizes your fortune.",
    "This is a strong period for deciding what you're saving toward. Savings with a purpose tend to stick.",
    "Rather than a windfall, it helps to focus on money that stays with you steadily. Building a small system pays off.",
    "When money worries hit, checking the actual numbers first tends to calm things down. Make the invisible anxiety visible.",
    "Your purse strings are a little loose right now. Enjoying treats within a set budget is the way to go.",
    "Your sensitivity to money-related information is rising. Rather than jumping at something interesting, research it first.",
    "The balance between saving and spending matters. Check whether you're leaning too far to one side right now.",
    "This is a good time to think about your future finances. Even a small savings rule moves you forward.",
    "Hints about money may come through conversations with people. Keep an antenna up for work, side jobs, and saving tips.",
    "Right now, a sure way to keep money beats an unnecessary gamble. The more solid your defense, the easier it is to act on the next chance.",
    "Your desire to grow your money is likely to strengthen. Don't rush — think about risk and return separately.",
    "Spending on things you're glad you bought raises both satisfaction and your fortune.",
    "Small expenses tend to pile up during this period. Take one look at your subscriptions and convenience-store spending.",
    "This is a good time to build the foundation of your fortune. Organizing your wallet, accounts, and payment methods will settle your mind too.",
    "This is a good flow for searching out ways to raise your income. Rather than earning immediately, focus on increasing your options.",
    "Watch out for money spent just because others swayed you. Check whether it's really something you want.",
    "Your decisions about spending money tend to come fast. Before deciding on the spot, ask if you'll still want it tomorrow.",
    "Your fortune is gradually trending upward. Continuing small actions could add up to a big difference later.",
    "This is a good time to set a savings goal. Making a rule matters more than the amount itself right now.",
    "Your individuality is showing in how you use money. Rather than comparing with others, choosing a management method that suits you works better.",
    "Rather than a single big win, preparation that raises your odds of winning suits you now. Research and planning support your fortune.",
    "Cherishing what you already have could cut down on unnecessary spending. Take stock of what you own before buying more.",
    "This is a period when you can face money matters instead of avoiding them. Just knowing where you stand starts to bring your fortune into order.",
    "Cutting small waste can bring back a sense of ease. Small improvements really do add up.",
    "Switching between offense and defense matters right now. Separating when to spend and when to keep stabilizes your fortune.",
    "No need to rush because of others' success stories. Sorting things out at your own pace ends up stronger in the end.",
    "You don't need to manage your money perfectly. Just getting a rough grasp of things is already progress.",
    "This looks like a good period for a solid purchase. Even better if you judge it by how long you'll actually use it.",
    "Hints for side income or a raise are easy to find right now. Look lightly into something you're interested in.",
    "Right now, your fortune responds a little each time you take action. Value each small step.",
    "The power to grow money starts by first building the power to protect it. No need to rush — focus on building a system that lets you keep more.",
    "Your fortune is in a state that's quite easy to shape. Mixing in calm judgment along with momentum takes it up another level.",
  ],
  "work-style": [
    "You're the type who can perform steadily within a set flow. Building your own go-to work pattern first makes you strong.",
    "You don't need to stand out flashily — your work fortune builds trust through daily consistency.",
    "This is a period when your sense of stability is likely to be valued. Careful continuation leads to results more than a sudden gamble.",
    "You have the power to support from behind the scenes. Tidying up the parts no one else notices helps the whole team run smoothly.",
    "Your strength shows in detailed work and catching oversights. It looks modest, but it's quite an important role.",
    "Your presence as a support role is likely to stand out right now. Noticing the troubles of those around you is a real talent.",
    "You have the power to keep steadily moving forward. Even without instant results, what you build up gets recognized later.",
    "You're the type who builds trust by carefully finishing the task in front of you. No need to rush.",
    "You have the power to build harmony with those around you. A role that steps between people and softens the mood suits you.",
    "You're good at organizing information and communicating it clearly. You're a huge help in meetings and shared work.",
    "You're the type who can get hands-on when there's trouble. Rather than overthinking, taking one step forward tends to reveal a breakthrough.",
    "You have a strong sense for the field. Your strength is thinking about how things actually move, not just theory on paper.",
    "You have the power to close the distance with people. You're the type who can build work momentum out of conversation and small talk.",
    "You have the power to move work forward through communication. You seem good at reading the other person's mood.",
    "A role coordinating schedules and people's circumstances suits you. You can become an indispensable coordinator for the team.",
    "You have an eye for balance among the people around you. Noticing when someone is pushing themselves too hard is also a talent.",
    "You have the power to warm up the mood of a room. A mood-maker role that eases tension suits you.",
    "You can create an atmosphere where people feel comfortable talking. Work results often come from that kind of reassurance.",
    "You're the type who easily comes up with new ideas. Just slightly tweaking an existing method could lead to an interesting outcome.",
    "Your idea-generating power runs strong. Jotting down whatever comes to mind can later become a proposal or improvement.",
    "You have the power to read numbers and situations. Your strength is judging based on evidence rather than feeling alone.",
    "You tend to shine as an analyst. A calm perspective is especially valuable when everyone around you is moving on emotion.",
    "You give off an approachable vibe that invites people to consult you. The ability to hold space for someone, not just give answers, is also a talent at work.",
    "You have a steady presence as a listener. You're the type who naturally moves things toward a solution while organizing what people say.",
    "You have the power to push tasks forward. Being conscious of deadlines and order makes you someone people rely on heavily.",
    "Progress management suits you. Making tasks visible helps the whole team move more smoothly.",
    "You have the power to stand between management and the field. You can translate words into a form everyone can act on.",
    "You're quite strong as a strategist. Even without stepping too far forward, you're the type who can shape the flow from behind the scenes.",
    "Your power to bring a team together is showing. Communicating direction clearly helps everyone move more easily.",
    "You have a leadership temperament. Your strength isn't just pulling people along, but judging while seeing the whole picture.",
    "You're not the type who fits neatly into an ordinary method. The more freedom you have, the more your ideas and drive grow.",
    "You have the power to carve a new path. Rather than waiting for instructions, trying things yourself tends to lead to results.",
    "You have breakthrough power. You're the type who can push something not yet fully formed forward through momentum and ingenuity.",
    "You shine in an environment with discretion. You perform better when trusted with something than when managed in detail.",
    "You have a bird's-eye perspective. You're the type who thinks about the flow and purpose, not just the task in front of you.",
    "You have the qualities of a decision-maker. Being able to decide what to prioritize when you're unsure is a major strength.",
    "At work, you perform better once your role is clear. Try to find the position where your strengths fit best.",
    "Your current work fortune grows a lot based on how you mesh with those around you. It helps to notice where you can be useful.",
    "You don't need to force yourself to be all-around capable. Growing your strong position leads to recognition more effectively.",
    "Talent at work isn't just one thing. Supporting, thinking, moving things, and organizing are all legitimate strengths.",
  ],
  "dark-fall": [
    "Small shadows are starting to gather deep in your heart. Some light still remains.",
    "Even while smiling, a small meeting of darkness is starting inside.",
    "The more you hide dark feelings, the more little stardust accumulates in your inner universe.",
    "The part of you that wants to be kind and the part that doesn't want to expect anything anymore are quietly swaying.",
    "The quieter you are, the more you might actually be sinking to a deep place inside.",
    "You say you're still fine while glancing a little at the entrance to darkness.",
    "Being skilled at pretending you're fine means you're slower to notice your own exhaustion.",
    "Every time you swallow a small discomfort, a little more black ink spreads inside.",
    "Not expecting things from people might be a defense to protect yourself.",
    "Behind your brightness, you're the type quietly carrying a calm kind of darkness.",
    "Painful memories keep orbiting inside you like a small planet.",
    "Even pretending to forget something unpleasant, it stays in your mental notebook.",
    "When you doubt someone's kindness, it's often an old wound still reacting.",
    "Getting too used to loneliness can make it hard to find the moment to say \"help.\"",
    "The more you want to close the door of your heart, the more you're actually searching for somewhere safe.",
    "On the nights you overthink the most, your rate of generating dark poetry speeds up.",
    "When you're worn out from being kind for too long, a slightly darker version of you peeks through.",
    "Even if you think you've sealed your emotions, they still show at the corners of your eyes.",
    "Falling into darkness isn't sudden — it approaches through small accumulated moments of holding back.",
    "Not denying the dark feelings inside you is the first step to coming back.",
    "There are days when lining up bright words doesn't quite bring your heart along.",
    "For every wound, a slightly calmer, slightly stronger version of you grows.",
    "When your kindness is treated carelessly, one star in your heart dims at a time.",
    "Every time you recall a past failure, a replay screen opens in your mind.",
    "You're actually angry, but staying quiet is how you hold yourself together.",
    "People carrying deep darkness are sometimes especially weak to someone's small kindness.",
    "Even if a black hole forms in your heart, you don't have to drop everything into it.",
    "Doubt protects you, but too much of it pushes away even your allies.",
    "Feelings you can't tell anyone tend to grow a little bigger at night.",
    "Finding beauty in something about to break is a sign your heart is a little tired.",
    "Carrying darkness and being swallowed by darkness are different things. You can still choose.",
    "The longer you keep hiding your true feelings, the heavier the black crown in your heart grows.",
    "People who don't show their anger are the ones who sometimes suddenly distance themselves one day.",
    "If you can put dark feelings into words, that itself becomes a source of recovery.",
    "You might be acting a little cold just to protect your hurting self.",
    "People who have seen the depths of the abyss sometimes can't come back with light encouragement alone.",
    "When you're in the middle of darkness, you don't have to force yourself to look bright.",
    "Even dark feelings have their reasons. Start by naming them without blame.",
    "Even while saying you won't expect anything anymore, part of you still wants to believe.",
    "Precisely because you've known deep darkness, the light feels stronger once you find your way back.",
  ],
  "life-bug": [
    "You think you're living a normal life, yet somehow an event keeps happening.",
    "Life's screenwriter might be goofing off sometimes.",
    "It looks like you picked the wrong option, but it ends up as good material anyway.",
    "Even when trouble happens, it somehow always gets wrapped up as a good story in the end.",
    "You thought you chose the peaceful route, but a side event suddenly kicks off.",
    "You carry a bit of a fate that won't let you have an ordinary life.",
    "Even after failing, people around you somehow turn it into something to laugh about.",
    "The difficulty setting of your life sometimes just goes up on its own.",
    "It's less main-character plot armor and more \"gets-dragged-into-events\" armor.",
    "One way or another, your survival instinct is strong. That's less a bug and more a talent.",
    "You just want an ordinary day, yet a small incident keeps happening.",
    "Your life's save points seem to be in strange places.",
    "A choice you thought was a mistake sometimes turns into foreshadowing later.",
    "It looks rough from the outside, but you're gradually getting used to it.",
    "Things not going according to plan has basically become your normal setting.",
    "You have the strength to shrug things off with \"there it goes again.\"",
    "Your life has a lot of mysterious random events.",
    "You're walking down a normal path, but you keep getting pulled into side-quest events.",
    "Your tolerance for trouble has been quietly building without you noticing.",
    "You sometimes get dragged into things before you even reach a choice.",
    "Your life's tutorial seems to be set closer to hard mode.",
    "Being able to turn a failure into a funny story is a talent.",
    "It looks like coincidence, but you keep drawing pretty intense events every time.",
    "Even when you choose peace, the story itself seems to hype things up on its own.",
    "You seem to have more life episodes than the people around you.",
    "You're just acting normal, yet somehow you end up at the center of the story.",
    "Your ability to shift gears when trouble hits is oddly fast.",
    "In the end, you turn your life's bugs into part of your character.",
    "Your luck looks bad, but you also have the luck of just barely getting saved.",
    "You're the type whose storyline can suddenly develop fast.",
    "A huge amount of material comes out of a single incident for you.",
    "You seem to attract intense people or intense events for some reason.",
    "Your life's random number generator runs a little wild.",
    "In situations that would normally get someone down, you eventually turn it into a laugh.",
    "You think you're ordinary, but from the outside your life looks quite eventful.",
    "You have a knack for strange developments at strange timings.",
    "Only your event-occurrence rate seems to have a high game setting.",
    "\"Why me\" eventually turns into \"well, at least it's material.\"",
    "Because your life has a lot of detours, you also have a lot of stories to tell.",
    "You've built up quite an immunity to unexpected events.",
    "You're glitchy, yet somehow a lovable type.",
    "You're doing everything seriously, yet somehow it ends with a punchline.",
    "Having a lot to comment on in your life has just become your personality.",
    "Even after failing, it doesn't end there — it connects to the next story.",
    "You have so many events that an ordinary day has become the rare one.",
    "When you tell people about your life, they're usually a little surprised.",
    "With some mysterious pull, you keep drawing in intense developments.",
    "Rather than fixing your life's bugs, you're heading toward mastering them instead.",
    "The wish to live normally and the reality of never quite ending normally are in conflict.",
    "In the end, you turn every event into your own story.",
    "Plenty of mishaps happen, yet somehow it all comes together in the end.",
    "You might be a little bit favored by life's game master.",
    "Somehow, things happen to you that make people ask, \"does that normally happen?\"",
    "Life glitches out on you sometimes, but your ability to handle it glitches out just as much, in a good way.",
    "Because you take a lot of detours, you've built up quite a lot of experience points.",
    "Even doing nothing in particular, the story somehow gets interesting on its own.",
    "Every time you get dragged into an event, your main-character energy grows.",
    "You're not the type who gets to end on an ordinary ending.",
    "You're a pretty strong player, turning even trouble into material.",
    "It's less a life bug and more a strong case of story plot armor.",
  ],
}
